apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: usuue0mpj-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: usuue0mpj-python 
  name: usuue0mpj-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: usuue0mpj-python 
